In [7]:
import numpy as np
import os
import pandas as pd
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func, inspect

import json

In [22]:
engine = create_engine("sqlite:///bellybutton.sqlite")
conn = engine.connect()
inspector = inspect(engine)

In [24]:
for table_name in inspector.get_table_names():
    for column in inspector.get_columns(table_name):
        print("Column: %s" % column['name'])
        print(table_name)

Column: sample
sample_metadata
Column: EVENT
sample_metadata
Column: ETHNICITY
sample_metadata
Column: GENDER
sample_metadata
Column: AGE
sample_metadata
Column: WFREQ
sample_metadata
Column: BBTYPE
sample_metadata
Column: LOCATION
sample_metadata
Column: COUNTRY012
sample_metadata
Column: ZIP012
sample_metadata
Column: COUNTRY1319
sample_metadata
Column: ZIP1319
sample_metadata
Column: DOG
sample_metadata
Column: CAT
sample_metadata
Column: IMPSURFACE013
sample_metadata
Column: NPP013
sample_metadata
Column: MMAXTEMP013
sample_metadata
Column: PFC013
sample_metadata
Column: IMPSURFACE1319
sample_metadata
Column: NPP1319
sample_metadata
Column: MMAXTEMP1319
sample_metadata
Column: PFC1319
sample_metadata
Column: otu_id
samples
Column: otu_label
samples
Column: 940
samples
Column: 941
samples
Column: 943
samples
Column: 944
samples
Column: 945
samples
Column: 946
samples
Column: 947
samples
Column: 948
samples
Column: 949
samples
Column: 950
samples
Column: 952
samples
Column: 953
samples
Column: 954
samples
Column: 955
samples
Column: 956
samples
Column: 958
samples
Column: 959
samples
Column: 960
samples
Column: 961
samples
Column: 962
samples
Column: 963
samples
Column: 964
samples
Column: 966
samples
Column: 967
samples
Column: 968
samples
Column: 969
samples
Column: 970
samples
Column: 971
samples
Column: 972
samples
Column: 973
samples
Column: 974
samples
Column: 975
samples
Column: 978
samples
Column: 1233
samples
Column: 1234
samples
Column: 1235
samples
Column: 1236
samples
Column: 1237
samples
Column: 1238
samples
Column: 1242
samples
Column: 1243
samples
Column: 1246
samples
Column: 1253
samples
Column: 1254
samples
Column: 1258
samples
Column: 1259
samples
Column: 1260
samples
Column: 1264
samples
Column: 1265
samples
Column: 1273
samples
Column: 1275
samples
Column: 1276
samples
Column: 1277
samples
Column: 1278
samples
Column: 1279
samples
Column: 1280
samples
Column: 1281
samples
Column: 1282
samples
Column: 1283
samples
Column: 1284
samples
Column: 1285
samples
Column: 1286
samples
Column: 1287
samples
Column: 1288
samples
Column: 1289
samples
Column: 1290
samples
Column: 1291
samples
Column: 1292
samples
Column: 1293
samples
Column: 1294
samples
Column: 1295
samples
Column: 1296
samples
Column: 1297
samples
Column: 1298
samples
Column: 1308
samples
Column: 1309
samples
Column: 1310
samples
Column: 1374
samples
Column: 1415
samples
Column: 1439
samples
Column: 1441
samples
Column: 1443
samples
Column: 1486
samples
Column: 1487
samples
Column: 1489
samples
Column: 1490
samples
Column: 1491
samples
Column: 1494
samples
Column: 1495
samples
Column: 1497
samples
Column: 1499
samples
Column: 1500
samples
Column: 1501
samples
Column: 1502
samples
Column: 1503
samples
Column: 1504
samples
Column: 1505
samples
Column: 1506
samples
Column: 1507
samples
Column: 1508
samples
Column: 1510
samples
Column: 1511
samples
Column: 1512
samples
Column: 1513
samples
Column: 1514
samples
Column: 1515
samples
Column: 1516
samples
Column: 1517
samples
Column: 1518
samples
Column: 1519
samples
Column: 1521
samples
Column: 1524
samples
Column: 1526
samples
Column: 1527
samples
Column: 1530
samples
Column: 1531
samples
Column: 1532
samples
Column: 1533
samples
Column: 1534
samples
Column: 1535
samples
Column: 1536
samples
Column: 1537
samples
Column: 1539
samples
Column: 1540
samples
Column: 1541
samples
Column: 1542
samples
Column: 1543
samples
Column: 1544
samples
Column: 1545
samples
Column: 1546
samples
Column: 1547
samples
Column: 1548
samples
Column: 1549
samples
Column: 1550
samples
Column: 1551
samples
Column: 1552
samples
Column: 1553
samples
Column: 1554
samples
Column: 1555
samples
Column: 1556
samples
Column: 1557
samples
Column: 1558
samples
Column: 1561
samples
Column: 1562
samples
Column: 1563
samples
Column: 1564
samples
Column: 1572
samples
Column: 1573
samples
Column: 1574
samples
Column: 1576
samples
Column: 1577
samples
Column: 1581
samples
Column: 1601
samples

In [25]:
Base = automap_base()
Base.prepare(engine, reflect=True)
print(Base.classes.keys())

Sample_metadata = Base.classes.sample_metadata
Samples = Base.classes.samples
session=Session(engine)

['sample_metadata', 'samples']

In [26]:
datax = pd.read_sql("SELECT * FROM samples",conn)
metadata = pd.read_sql("SELECT * FROM sample_metadata",conn)

In [27]:
otu_id=datax['otu_id'].tolist()
otu_label=datax['otu_label'].tolist()

In [28]:
dataxx=datax.drop(["otu_id","otu_label"],1)

In [29]:
valuex = dataxx.values.tolist()
dataB={"otu_id" : otu_id, "sample_values" : valuex, "out_label" : otu_label}
dataJ = json.dumps(dataB)
names = list(dataxx.columns)

In [30]:
names[1]

'941'

In [13]:
nj=json.dumps(names)

In [32]:
# dataxx

In [34]:
datax
sample_datax = datax.set_index(["otu_id","otu_label"])

In [39]:
# sample_datax

In [40]:
names = list(sample_datax.columns)

In [41]:
names

['940',
 '941',
 '943',
 '944',
 '945',
 '946',
 '947',
 '948',
 '949',
 '950',
 '952',
 '953',
 '954',
 '955',
 '956',
 '958',
 '959',
 '960',
 '961',
 '962',
 '963',
 '964',
 '966',
 '967',
 '968',
 '969',
 '970',
 '971',
 '972',
 '973',
 '974',
 '975',
 '978',
 '1233',
 '1234',
 '1235',
 '1236',
 '1237',
 '1238',
 '1242',
 '1243',
 '1246',
 '1253',
 '1254',
 '1258',
 '1259',
 '1260',
 '1264',
 '1265',
 '1273',
 '1275',
 '1276',
 '1277',
 '1278',
 '1279',
 '1280',
 '1281',
 '1282',
 '1283',
 '1284',
 '1285',
 '1286',
 '1287',
 '1288',
 '1289',
 '1290',
 '1291',
 '1292',
 '1293',
 '1294',
 '1295',
 '1296',
 '1297',
 '1298',
 '1308',
 '1309',
 '1310',
 '1374',
 '1415',
 '1439',
 '1441',
 '1443',
 '1486',
 '1487',
 '1489',
 '1490',
 '1491',
 '1494',
 '1495',
 '1497',
 '1499',
 '1500',
 '1501',
 '1502',
 '1503',
 '1504',
 '1505',
 '1506',
 '1507',
 '1508',
 '1510',
 '1511',
 '1512',
 '1513',
 '1514',
 '1515',
 '1516',
 '1517',
 '1518',
 '1519',
 '1521',
 '1524',
 '1526',
 '1527',
 '1530',
 '1531',
 '1532',
 '1533',
 '1534',
 '1535',
 '1536',
 '1537',
 '1539',
 '1540',
 '1541',
 '1542',
 '1543',
 '1544',
 '1545',
 '1546',
 '1547',
 '1548',
 '1549',
 '1550',
 '1551',
 '1552',
 '1553',
 '1554',
 '1555',
 '1556',
 '1557',
 '1558',
 '1561',
 '1562',
 '1563',
 '1564',
 '1572',
 '1573',
 '1574',
 '1576',
 '1577',
 '1581',
 '1601']